version: "3"
services:
  db:
    image: postgres:10
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=testdb
    volumes:
      - C:\Users\irmsc\pp\npd2\scripts:/docker-entrypoint-initdb.d/
    expose:
      - 5432
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/home/app/
    depends_on:
      - db